#pragma once
void lesok();
void naumova_fast();
void naumova();
void abba();
void abc();
void abc_fast();
void gnom();
void maiz();
void p2020();
void you();
void putin();
void eng_math();
void shad_2021();
void udar();
void rabota();
void buketik();
void futbol();
